const ethnicities = [
    "Hispanic/Latino",
    "Arab",
    "Ashkenazi Jewish",
    "Sephardic Jewish",
    "Han Chinese",
    "Punjabi",
    "Bengali",
    "Pashtun",
    "Tamil",
    "Kurdish",
    "Igbo",
    "Yoruba",
    "Zulu",
    "Maori",
    "Native American",
    "Inuit",
    "Japanese",
    "Korean",
    "Thai",
    "Vietnamese",
    "Russian",
    "Ukrainian",
    "Greek",
    "Irish",
    "Scottish",
    "Italian",
    "German",
    "Polish",
    "French",
    "Turkish",
    "Persian (Iranian)",
    "Afghan",
    "Somali",
    "Ethiopian",
    "Brazilian",
    "Mexican",
    "Guatemalan",
    "Haitian",
    "Filipino",
    "Malay",
    "Indonesian"
  ];
  
  export const ethenityData = {
    ethnicities
  }  